### ISSUE TITLE
Non-unique resource names generated

### ISSUE THREAD

**Issue by huyz** [cloudflare/cf-terraforming#893]
### Confirmation

- [x] My issue isn't already found on the issue tracker.
- [x] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

v0.23.3-dev+802c81227453

### Expected outcome

For at least 4 different resource types, `cf-terraforming generate` creates multiple blocks with non-unique resource names. All resource names generated need to be unique or Terraform will complain (and prevent further execution of `cf-terraforming`)

The resource types are: `cloudflare_tiered_cache`, `cloudflare_argo_tiered_caching`, `cloudflare_email_routing_dns`, `cloudflare_zero_trust_device_default_profile_local_domain_fallback`

## Pattern 1

```hcl
resource "cloudflare_tiered_cache" "terraform_managed_resource_tiered_cache_smart_topology_enable" {
  value   = "on"
  zone_id = "__REDACTED__"
}
resource "cloudflare_argo_tiered_caching" "terraform_managed_resource_tiered_caching" {
  value   = "off"
  zone_id = "__REDACTED__"
}
```
The resource names are clearly missing a unique ID.

## Pattern 2

```hcl
resource "cloudflare_email_routing_dns" "terraform_managed_resource_bcb16a83c46864__REDACTED__" {
  name    = "cf2024-1._domainkey.__REDACTED_DOMAIN_NAME__"
  zone_id = "__REDACTED__"
}

resource "cloudflare_email_routing_dns" "terraform_managed_resource_bcb16a83c46864__REDACTED__" {
  name    = "__REDACTED_DOMAIN_NAME__"
  zone_id = "__REDACTED__"
}

resource "cloudflare_zero_trust_device_default_profile_local_domain_fallback" "terraform_managed_resource_d89f70396a74b__REDACTED__" {
  account_id = "__REDACTED__"
  domains = [{
    suffix = "home.arpa"
  }]
}

resource "cloudflare_zero_trust_device_default_profile_local_domain_fallback" "terraform_managed_resource_d89f70396a74b__REDACTED__" {
  account_id = "__REDACTED__"
  domains = [{
    suffix = "intranet"
  }]
}
```

Here the resource names have what look like unique IDs, but multiple blocks are output with the same ID, so Terraform will complain about that too.

### Steps to reproduce

On macOS 14.7.6 23H626 (Sonoma) MacBookPro18,2 (Apple M1 Max, arm64):

1. Install Terraform v1.5.7 
1. Install Terraform Cloudflare provider v5.6.0
1. Build `cf-terraforming` from source: v0.23.3-dev+802c81227453
1. Run `cf-terraforming generate --resource-type` with resource types `cloudflare_tiered_cache`, `cloudflare_argo_tiered_caching`, `cloudflare_email_routing_dns`, `cloudflare_zero_trust_device_default_profile_local_domain_fallback`
1. Now you can't even run `cf-terraforming` anymore as terraform will fail.

**Comment by jhutchings1** [comment]
Thanks for reporting, we can have a look, there may be a regression here.

**Comment by huyz** [comment]
@vaishakdinesh I will today. Thanks for addressing all the GitHub Issues. Happy to see you engaged!  I will do a thorough test of many different resources and report back soon.

**Comment by huyz** [comment]
@vaishakdinesh  Ok running the latest from master: v0.23.3-dev+0e16036027f2

Nothing's fixed. (I see a lot of fixes for other resources though, just not these 4.)

Definitely still a problem for:
- `cloudflare_tiered_cache` -- Note that for this resource, there is no problem for the v4 provider (unique resource names are properly generated)
- `cloudflare_argo_tiered_caching` -- This is broken for v4 provider as well
- `cloudflare_email_routing_dns`
- `cloudflare_zero_trust_device_default_profile_local_domain_fallback`

**Comment by vaishakdinesh** [comment]
@huyz thank you for the update! I'll look into these and let you know when there's a fix.

**Comment by vaishakdinesh** [comment]
@huyz merged a fix

**Comment by huyz** [comment]
@vaishakdinesh Great! I wrote up a suggestion: https://github.com/cloudflare/cf-terraforming/pull/905#pullrequestreview-2963935797

**Comment by huyz** [comment]
@vaishakdinesh Also I'm a bit confused by the output for `cloudflare_zero_trust_device_default_profile_local_domain_fallback`.

I'm getting this for `generate`:

```hcl
resource "cloudflare_zero_trust_device_default_profile_local_domain_fallback" "terraform_managed_resource_REDACTED_ACCOUNT_ID_0" {
  account_id = "REDACTED_ACCOUNT_ID"
  domains = [{
    suffix = "home.arpa"
  }]
}

resource "cloudflare_zero_trust_device_default_profile_local_domain_fallback" "terraform_managed_resource_REDACTED_ACCOUNT_ID_1" {
  account_id = "REDACTED_ACCOUNT_ID"
  domains = [{
    suffix = "intranet"
  }]
}

resource "cloudflare_zero_trust_device_default_profile_local_domain_fallback" "terraform_managed_resource_REDACTED_ACCOUNT_ID_2" {
  account_id = "REDACTED_ACCOUNT_ID"
  domains = [{
    suffix = "internal"
  }]
}

…
```

and I'm wondering perhaps if they should just be combined into a single resource block but all the suffixes should be added into a single `domains` field (I'm not familiar with this resource so I don't know):

```
resource "cloudflare_zero_trust_device_default_profile_local_domain_fallback" "terraform_managed_resource_REDACTED_ACCOUNT_ID" {
  account_id = "REDACTED_ACCOUNT_ID"
  domains = [{
    suffix = "home.arpa"
  },
  {
    suffix = "intranet"
  },
  {
    suffix = "internal"
  },
  …
  ]
}
``

**Comment by vaishakdinesh** [comment]
@huyz Thank you for the suggestion, But i think there's a wholistic value in keeping the name generated as it is. It may be a ittle verbose, but i think its fine as it is.

> and I'm wondering perhaps if they should just be combined into a single resource block but all the suffixes should be added into a single domains field (I'm not familiar with this resource so I don't know):

That wouldn't work when you'd want to maintain those resources. If that's the desired outcome, youd wanna configure the local domain fallback like that instead of the 3 objects. 

Since the original issue is addressed, @huyz can we close this?

**Comment by huyz** [comment]
@vaishakdinesh Still doesn't work.

`generate` produces resource names that look like this:
```
resource "cloudflare_email_routing_dns" "terraform_managed_resource_bcb16a83c…346f_0" {
```

while `import` produces resource names that look like this:
```
  to = cloudflare_email_routing_dns.terraform_managed_resource_0
```
where the ID is clearly missing.
